name: Tester

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  linuxbuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir src/build && cd src/build && cmake ..
    - name: build
      run: cmake --build src/build
    - name: tester
      run: src/build/tester
    - name: testerCI
      run: src/build/testerCI
